package com.suri.leetcode.easy;

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
https://leetcode.com/problems/find-the-difference/
 */
public class Soln_389_Find_the_Difference {
    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd", "abcde"));
    }

    public static char findTheDifference(String s, String t) {
        int[] sarr = new int[26];
        int [] tarr = new int[26];
        for(int i=0;i<s.length(); i++){
            sarr[s.charAt(i)-'a']++;
        }
        for(int i=0;i<t.length(); i++){
            tarr[t.charAt(i)-'a']++;
        }
        for(int i=0; i<26; i++){
            if(tarr[i]!=sarr[i]){
                return (char)(97+i);
            }
        }
        return '0';
    }

    // optimized approach
    public static char findTheDifference1(String s, String t) {
        char xor1 =0;
        for(char ch : s.toCharArray()){
            xor1^= ch;
        }
        char xor2 =0;

        for(char ch : t.toCharArray()){
            xor2^= ch;
        }
        return (char)(xor1^xor2);
    }

}
